config/routes.rb
Rails.application.routes.draw do
  resources :foods
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'pages/show'
  devise_for :users, :controllers => {
    :registrations => "registrations"
  }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.where("user_id = ?" ,current_user.id)
                .page(params[:page])
                .per(10)
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def food_params
      params.require(:food).permit(:user_id, :name, :best_before, :expiry_date, :is_consumed)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/foods/_form.html.erb
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

<%= form_with(model: food, local: true) do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- TODO: Controllerかmodelでログイン中のユーザーIDを取得するように変更する -->
  <input type="hidden" name="food[user_id]" id="food_user_id" value="<%= current_user.id %>">

  <div class="field">
    <%= form.label "食べ物の名前" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label "賞味期限" %>
    <%= form.text_field :best_before , class: "datepicker" %>
  </div>

  <div class="field">
    <%= form.label "消費期限" %>

    <%= form.text_field :expiry_date , class: "datepicker" %>
  </div>

  <div class="field">
    <%= form.label "もう食べた" %>
    <%= form.check_box :is_consumed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>
  $(".datepicker").datepicker({
        dateFormat: 'yy-mm-dd',
  });
</script>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<%
def get_btn_class_by_date(date)
  to_exp = (Date.parse(date.to_s) - Date.today).to_i
  if to_exp <= 0
    return "btn-danger"
  elsif to_exp <= 3
    return "btn-warning"
  else
    return "btn-success"
  end
end
%>
<p id="notice"><%= notice %></p>

<h1>Foods</h1>

<table>
  <thead>
    <tr>
      <th>食べ物の名前</th>
      <th>賞味期限</th>
      <th>消費期限</th>
      <th>もう食べた</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><p class="btn <%= get_btn_class_by_date(food.best_before) unless food.best_before.nil? %> btn-sm"><%= food.best_before %></p></td>
        <td><p class="btn <%= get_btn_class_by_date(food.expiry_date) unless food.expiry_date.nil? %> btn-sm"><%= food.expiry_date %></p></td>
        <td><%= food.is_consumed %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @foods %>
<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @food.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Best before:</strong>
  <%= @food.best_before %>
</p>

<p>
  <strong>Expiry date:</strong>
  <%= @food.expiry_date %>
</p>

<p>
  <strong>Is consumed:</strong>
  <%= @food.is_consumed %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodExpiryDate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>

  <body>
    <header>
      <nav>
          <% if user_signed_in? %>
            <strong><%= link_to current_user.name, pages_show_path %></strong>
            <%= link_to 'プロフィール変更', edit_user_registration_path %>
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'サインアップ', new_user_registration_path %>
            <%= link_to 'ログイン', new_user_session_path %>
          <% end %>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>ようこそ</h1>
<p>トップページです。</p>
<%= link_to 'メイン画面はこちら', foods_path %>

app/views/pages/show.html.erb
<h1>こんにちは、<%= current_user.email %>さん</h1>
<p>ユーザー用ページです。</p>